#!/bin/sh
# git hook to ensure code style
# cp tools/git-pre-commit .git/hooks/pre-commit

which >/dev/null pep8 || (echo "please install pep8"; exit )
files=$(git diff --name-only --staged --diff-filter=ACMRTUXB | egrep "*.py$")

if test -n "$files"; then
  pep8 --max-line-length=120 $files
  res=$?
  if [ $res -ne 0 ]; then
    echo
    autopep8 --max-line-length=120 --diff $files
    echo
    echo "To fix run: autopep8 --max-line-length=120 -i $files"
  fi
  exit $res
fi
